=== s1dam-azarquiel-2021/aru-xml/liga-futbol/liga-futbol.dtd
<!ELEMENT liga-futbol (equipos,jornadas)>

<!ELEMENT equipos (equipo+)>

<!ELEMENT equipo EMPTY>
<!ATTLIST equipo nombre ID #REQUIRED>
<!ATTLIST equipo id-escudo CDATA #REQUIRED>

<!ELEMENT jornadas (jornada+)>
<!ATTLIST jornada numero CDATA #REQUIRED>
<!ELEMENT jornada (partidos)>

<!ELEMENT partidos (partido+)>

<!ELEMENT partido (local, visitante)>
<!ATTLIST partido fecha CDATA #REQUIRED>

<!ELEMENT local (goles)>
<!ATTLIST local nombre IDREF #REQUIRED>

<!ELEMENT visitante (goles)>
<!ATTLIST visitante nombre IDREF #REQUIRED>

<!ELEMENT goles (#PCDATA)>

=== s1dam-azarquiel-2021/aru-xml/liga-futbol/liga-futbol.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="liga-futbol.xsl" type="text/xsl"?>
<!DOCTYPE liga-futbol SYSTEM "liga-futbol.dtd">
<liga-futbol>
	<equipos>
		<equipo nombre="RealSociedad" id-escudo="188" />
		<equipo nombre="Betis"        id-escudo="185" />
		<equipo nombre="Elche"        id-escudo="954" />
		<equipo nombre="Mallorca"     id-escudo="181" />
		<equipo nombre="Alaves"       id-escudo="173" />
		<equipo nombre="Rayo"         id-escudo="184" />
		<equipo nombre="Valencia"     id-escudo="191" />
		<equipo nombre="Osasuna"      id-escudo="450" />
		<equipo nombre="Getafe"       id-escudo="450" />
		<equipo nombre="Villarreal"   id-escudo="449" />
		<equipo nombre="Granada"      id-escudo="5683" />
		<equipo nombre="Levante"      id-escudo="855" />
		<equipo nombre="Atletico"     id-escudo="175" />
		<equipo nombre="Espanyol"     id-escudo="177" />
		<equipo nombre="Athletic"     id-escudo="174" />
		<equipo nombre="Celta"        id-escudo="176" />
		<equipo nombre="Sevilla"      id-escudo="179" />
		<equipo nombre="RealMadrid"   id-escudo="186" />
		<equipo nombre="Barcelona"    id-escudo="178" />
		<equipo nombre="Cadiz"        id-escudo="1737" />
	</equipos>
	<jornadas>
		<jornada numero="32">
			<partidos>
				<partido fecha="15/04/2022">
					<local nombre="RealSociedad"><goles>0</goles></local>
					<visitante nombre="Betis"><goles>0</goles></visitante>
				</partido>
				<partido fecha="16/04/2022">
					<local nombre="Elche"><goles>3</goles></local>
					<visitante nombre="Mallorca"><goles>0</goles></visitante>
				</partido>
				<partido fecha="16/04/2022">
					<local nombre="Alaves"><goles>1</goles></local>
					<visitante nombre="Rayo"><goles>0</goles></visitante>
				</partido>
				<partido fecha="16/04/2022">
					<local nombre="Valencia"><goles>1</goles></local>
					<visitante nombre="Osasuna"><goles>2</goles></visitante>
				</partido>
				<partido fecha="16/04/2022">
					<local nombre="Getafe"><goles>1</goles></local>
					<visitante nombre="Villarreal"><goles>2</goles></visitante>
				</partido>
				<partido fecha="17/04/2022">
					<local nombre="Granada"><goles>1</goles></local>
					<visitante nombre="Levante"><goles>4</goles></visitante>
				</partido>
				<partido fecha="17/04/2022">
					<local nombre="Atletico"><goles>2</goles></local>
					<visitante nombre="Espanyol"><goles>1</goles></visitante>
				</partido>
				<partido fecha="17/04/2022">
					<local nombre="Athletic"><goles>0</goles></local>
					<visitante nombre="Celta"><goles>2</goles></visitante>
				</partido>
				<partido fecha="17/04/2022">
					<local nombre="Sevilla"><goles>2</goles></local>
					<visitante nombre="RealMadrid"><goles>3</goles></visitante>
				</partido>
				<partido fecha="18/04/2022">
					<local nombre="Barcelona"><goles>0</goles></local>
					<visitante nombre="Cadiz"><goles>1</goles></visitante>
				</partido>
			</partidos>
		</jornada>
	</jornadas>
</liga-futbol>
