=== s1dam-azarquiel-2021/aru-xml/recetas/recetas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="recetas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="receta" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="receta">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"></xs:element>
        <xs:choice>
          <xs:element name="entrada"><xs:complexType/></xs:element>
          <xs:element name="principal"><xs:complexType/></xs:element>
          <xs:element name="postre"><xs:complexType/></xs:element>
        </xs:choice>
        <xs:element name="imagen" type="imagen" minOccurs="0"></xs:element>
        <xs:element ref="ingredientes"></xs:element>
        <xs:element ref="paso" minOccurs="0" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
      <xs:attribute name="tiempo" type="xs:positiveInteger"></xs:attribute>
      <xs:attribute name="comensales" type="xs:positiveInteger"></xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="imagen">
    <xs:restriction base="xs:string">
      <xs:pattern value="https?:\/\/[a-zA-Z\d\.-]+\.[a-z]{2,}(\/[\w\./-]*)?\.(png|jpe?g)"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="ingredientes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="item">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="cantidad" type="cantidad" use="required"></xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="cantidad">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d+(u|cu|m?[lg])"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="paso">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="necesario" type="necesario"></xs:attribute>
          <xs:attribute name="numero" type="xs:positiveInteger"></xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="necesario">
    <xs:restriction base="xs:string">
      <xs:enumeration value="si"></xs:enumeration>
      <xs:enumeration value="no"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== s1dam-azarquiel-2021/aru-xml/recetas/recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<recetas
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="recetas.xsd">
  <receta comensales="4">
    <titulo>Jamón</titulo>
    <entrada />
    <ingredientes>
      <item cantidad="400g">Jamón</item>
    </ingredientes> 
  </receta>
  <receta tiempo="60" comensales="6">
    <titulo>Cocido</titulo>
    <principal />
    <ingredientes> 
      <item cantidad="500g">garbanzos</item>
      <item cantidad="100g">tocino ibérico</item>
      <item cantidad="1u">patata</item>
      <item cantidad="1u">puerro</item>
      <item cantidad="2u">chorizos</item>
      <item cantidad="750ml">agua</item>
    </ingredientes>
    <paso necesario="si">Tener a mano todos los ingredientes y una olla exprés.</paso>
    <paso numero="1">Añadir todos los ingredientes a una olla exprés.</paso>
    <paso numero="2">Dejar cocer durante 50 minutos</paso>
  </receta>
  <receta tiempo="45" comensales="4">
    <titulo>Tarta de queso</titulo>
    <postre/>
    <imagen>https://www.dulcespostres.com/wp-content/uploads/2014/05/Tarta-de-queso-330x220.jpg</imagen>
    <ingredientes> 
      <item cantidad="3u">yogures naturales</item>
      <item cantidad="3u">huevos</item>
      <item cantidad="1cu">maicena</item>
      <item cantidad="125g">crema de queso</item>
      <item cantidad="6cu">azúcar</item>
    </ingredientes>
    <paso necesario="si">Tener a mano todos los ingredientes, la batidora y el recipiente para la tarta.</paso>
    <paso numero="1">Batir todos los ingredientes.</paso>
    <paso numero="2">Verter en un molde previamente caramelizado y cocer durante 13 minutos en el microondas a máxima potencia.</paso>
    <paso necesario="no">Servir cubierta de mermelada.</paso>
    <paso necesario='no'>Bon appétit!</paso>
  </receta>
</recetas>
